force_color_prompt=yes

short_host=elemt-9010

if [ "$color_prompt" = yes ]; then
    PS1="[\u@$short_host]\$ \e[30;1m\w\e[0m\n\$ "
else
    PS1="\u@$short_host\$ \w\n\$ "
fi
unset color_prompt force_color_prompt
